# Generated by Django 4.2.7 on 2023-12-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_chat_input_text_chat_model_response_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input', models.TextField()),
                ('model_response', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
